# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: mf_no_delete
version: '1.0'
author: 'Medienfeuer, Daniel Springer'
compile: 0

page:
  title: 'No Deleter'
  perm: mf_no_delete[]
  pjax: true
  #icon: rex-icon fa fa-hospital-o
  hidden: true  

requires:
    packages:
    
    redaxo: '>=5.0'
